apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <PVC_NAME>
  namespace: <NAMESPACE>
spec:
  storageClassName: <STORAGE_CLASS_NAME>
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
    storage: 1Gi
